import csv
import hashlib
import json
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "docs" / "ash-cosmology" / "r012-r016-science-remediation"


def _json(relative: str):
    return json.loads((PACKAGE / relative).read_text(encoding="utf-8"))


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def test_r012_r016_science_remediation_manifest_payload_matches_files():
    manifest = _json("manifest.json")

    assert manifest["package_name"] == "ASH_R012_R016_science_remediation_handoff"
    assert manifest["source_boundary"] == "Does not modify or manage the ASH-Model repository."
    assert manifest["file_count"] == len(manifest["files"])

    for entry in manifest["files"]:
        path = PACKAGE / entry["path"]
        assert path.is_file(), entry["path"]
        assert path.stat().st_size == entry["bytes"], entry["path"]
        assert _sha256(path) == entry["sha256"], entry["path"]


def test_r012_r016_science_remediation_key_results_and_boundaries():
    summary = _json("outputs/executive_numeric_summary.json")
    ash_fit = next(
        row for row in summary["best_fit_DESI_plus_Planck"] if row["model"] == "ash"
    )

    assert math.isclose(ash_fit["chi2"], 8.7989789979, rel_tol=0.0, abs_tol=1e-10)
    assert math.isclose(ash_fit["H0"], 67.2353371359, rel_tol=0.0, abs_tol=1e-10)
    assert math.isclose(ash_fit["Omega_m"], 0.3138192686, rel_tol=0.0, abs_tol=1e-10)
    assert math.isclose(ash_fit["w0_eff"], -0.7928088139, rel_tol=0.0, abs_tol=1e-10)
    assert math.isclose(ash_fit["wa_eff"], -0.8126357917, rel_tol=0.0, abs_tol=1e-10)

    s8 = summary["s8_calibration"]
    assert s8["alpha_mu_required_for_DESY3_S8"] < 0.0
    assert s8["S8_locked_alpha_mu_plus_0p07"] > s8["S8_background_only"]
    assert math.isclose(s8["S8_calibrated"], 0.772, rel_tol=0.0, abs_tol=1e-8)

    assessments = {
        row["prediction_id"]: row["assessment"]
        for row in summary["locked_prediction_pilot_assessments"]
    }
    assert assessments == {
        "ASH-R015-P001": "not_confirmed_by_pilot_fit",
        "ASH-R015-P002": "tension_in_sign_and_magnitude_under_S8_proxy",
        "ASH-R015-P003": "sign_consistent_only",
    }

    report = (PACKAGE / "report" / "ASH_R012_R016_science_remediation_report.md").read_text(
        encoding="utf-8"
    )
    assert "This is still not a full ASH empirical validation." in report
    assert "not as supported predictions" in (PACKAGE / "executive_summary.md").read_text(
        encoding="utf-8"
    )


def test_r012_r016_science_remediation_desi_table_and_spectrum_are_finite_inputs():
    with (PACKAGE / "data" / "ash_pair_flip_spectrum.csv").open(newline="", encoding="utf-8") as f:
        spectrum = list(csv.DictReader(f))
    assert len(spectrum) == 9
    assert sum(int(row["multiplicity"]) for row in spectrum) == 256
    assert spectrum[1]["parity_shell"] == "odd"
    assert math.isclose(float(spectrum[1]["eta_lazy"]), 7.0 / 9.0, rel_tol=0.0, abs_tol=1e-12)

    with (PACKAGE / "data" / "desi_dr2_bao_compact_table_iv.csv").open(
        newline="", encoding="utf-8"
    ) as f:
        bao = list(csv.DictReader(f))
    assert [row["tracer"] for row in bao] == ["LRG1", "LRG2", "LRG3+ELG1", "ELG2", "QSO", "Lya"]
    assert all(float(row["rho_MH"]) < 0.0 for row in bao)


def test_r012_r016_science_remediation_has_no_attribution_language():
    forbidden = (
        "ai" + "-generated",
        "generated by " + "ai",
        "chat" + "gpt",
        "open" + "ai",
    )
    suffixes = {".csv", ".json", ".md", ".py", ".txt"}

    hits = []
    for path in PACKAGE.rglob("*"):
        if path.is_file() and path.suffix.lower() in suffixes:
            text = path.read_text(encoding="utf-8", errors="ignore").lower()
            for phrase in forbidden:
                if phrase in text:
                    hits.append((str(path.relative_to(PACKAGE)), phrase))

    assert hits == []
