"""ASH Model deterministic reference implementation.

The public surface deliberately separates:

* the 512-state hypercube :math:`F_2^9`;
* the parity-valid application-state hyperplane;
* the canonical rank-four doubly-even ``[9, 4, 4]`` transform code;
* the punctured ``[8, 4, 4]`` code used for the N=8 Adinkra quotient;
* deterministic feature, branch, reconstruction, and validation layers.
"""

from .bits import (
    BIT_COUNT,
    bits_to_int,
    flip_bit,
    hamming_distance,
    hamming_weight,
    int_to_bits,
    integrity_bit,
    is_integrity_valid,
    make_integrity_state,
    xor_bits,
)
from .background_bridge import (
    BackgroundParams,
    H_ash,
    angular_diameter_distance,
    branch_entropy_template,
    comoving_distance,
    convergence_diagnostics,
    distance_modulus,
    posterior_from_grid,
    run_validation as run_background_bridge_validation,
)
from .code import (
    CODEWORDS,
    GENERATOR_MATRIX,
    DecodeResult,
    decode,
    decode_affine,
    encode,
    translate,
)
from .cosmology import (
    FlatLambdaCDMParameters,
    compare_distance_baselines,
    dimensionless_hubble_parameter,
    flat_lcdm_distance_curve,
    normalized_comoving_distance,
)
from .empirical import (
    CalibratedObservable,
    LikelihoodResult,
    ObservableCalibration,
    calibrate_observable,
    chi_square,
    compare_gaussian_models,
    diagonal_gaussian_log_likelihood,
)
from .hypercube import (
    distance_shell,
    distance_shell_counts,
    even_parity_shell_counts,
    hypercube_adjacency_spectrum,
    hypercube_edge_count,
    hypercube_laplacian_spectrum,
    pair_flip_adjacency_spectrum,
    pair_flip_graph_degree,
    pair_flip_graph_edge_count,
    pair_flip_laplacian_spectrum,
)
from .physics import (
    BackgroundMoments,
    PhysicsObservables,
    background_moments,
    bridge_observables,
    evolve_weight_distribution,
    mixed_sector_eigenvalue,
    mixed_sector_transition,
    payload_pair_flip_eigenvalue,
    payload_pair_flip_transition,
    payload_state_space,
    payload_to_physical_state,
    pair_flip_transition,
    physical_state_space,
    sector_refresh_eigenvalue,
    sector_refresh_transition,
    uniform_background_distribution,
    uniform_physical_distribution,
    weight_level_degeneracies,
    weight_background_kernel,
)
from .prediction_ledger import (
    canonical_prediction_hash,
    ledger_lock_status,
    validate_prediction_ledger,
)
from .observer_commitment import (
    BOUNDARY_STATEMENT as OBSERVER_COMMITMENT_BOUNDARY_STATEMENT,
    LAW_VERSION as OBSERVER_COMMITMENT_LAW_VERSION,
    BranchRecord,
    ObserverCommitmentConfig,
    commit_memory,
    commitment_distribution,
    decoherence_entry,
    decoherence_summary,
    demo_expand_tree,
    frontier,
    memory_divergence,
    parent_memory_is_prefix,
    tree_distance,
    validate_probability_weights,
    verify_memory_prefix_embedding,
    verify_r009,
)

__all__ = [
    "BIT_COUNT",
    "CODEWORDS",
    "GENERATOR_MATRIX",
    "CalibratedObservable",
    "FlatLambdaCDMParameters",
    "PhysicsObservables",
    "BackgroundMoments",
    "BackgroundParams",
    "BranchRecord",
    "DecodeResult",
    "H_ash",
    "LikelihoodResult",
    "OBSERVER_COMMITMENT_BOUNDARY_STATEMENT",
    "OBSERVER_COMMITMENT_LAW_VERSION",
    "ObservableCalibration",
    "ObserverCommitmentConfig",
    "angular_diameter_distance",
    "bits_to_int",
    "background_moments",
    "branch_entropy_template",
    "calibrate_observable",
    "canonical_prediction_hash",
    "chi_square",
    "compare_distance_baselines",
    "compare_gaussian_models",
    "comoving_distance",
    "commit_memory",
    "commitment_distribution",
    "convergence_diagnostics",
    "decoherence_entry",
    "decoherence_summary",
    "decode",
    "decode_affine",
    "demo_expand_tree",
    "distance_shell",
    "distance_shell_counts",
    "distance_modulus",
    "diagonal_gaussian_log_likelihood",
    "dimensionless_hubble_parameter",
    "encode",
    "even_parity_shell_counts",
    "evolve_weight_distribution",
    "flat_lcdm_distance_curve",
    "flip_bit",
    "frontier",
    "hamming_distance",
    "hamming_weight",
    "hypercube_adjacency_spectrum",
    "hypercube_edge_count",
    "hypercube_laplacian_spectrum",
    "int_to_bits",
    "integrity_bit",
    "is_integrity_valid",
    "ledger_lock_status",
    "make_integrity_state",
    "memory_divergence",
    "bridge_observables",
    "mixed_sector_eigenvalue",
    "mixed_sector_transition",
    "normalized_comoving_distance",
    "payload_pair_flip_eigenvalue",
    "payload_pair_flip_transition",
    "payload_state_space",
    "payload_to_physical_state",
    "pair_flip_adjacency_spectrum",
    "pair_flip_graph_degree",
    "pair_flip_graph_edge_count",
    "pair_flip_laplacian_spectrum",
    "pair_flip_transition",
    "parent_memory_is_prefix",
    "physical_state_space",
    "posterior_from_grid",
    "run_background_bridge_validation",
    "sector_refresh_eigenvalue",
    "sector_refresh_transition",
    "translate",
    "tree_distance",
    "uniform_physical_distribution",
    "uniform_background_distribution",
    "validate_prediction_ledger",
    "validate_probability_weights",
    "verify_memory_prefix_embedding",
    "verify_r009",
    "weight_level_degeneracies",
    "weight_background_kernel",
    "xor_bits",
]

__version__ = "1.1.0"
