"""ASH Model deterministic reference implementation.

The public surface deliberately separates:

* the 512-state hypercube :math:`F_2^9`;
* the parity-valid application-state hyperplane;
* the canonical rank-four doubly-even ``[9, 4, 4]`` transform code;
* the punctured ``[8, 4, 4]`` code used for the N=8 Adinkra quotient;
* deterministic feature, branch, reconstruction, and validation layers.
"""

from .bits import (
    BIT_COUNT,
    bits_to_int,
    flip_bit,
    hamming_distance,
    hamming_weight,
    int_to_bits,
    integrity_bit,
    is_integrity_valid,
    make_integrity_state,
    xor_bits,
)
from .background_bridge import (
    BackgroundParams,
    H_ash,
    angular_diameter_distance,
    branch_entropy_template,
    comoving_distance,
    convergence_diagnostics,
    distance_modulus,
    posterior_from_grid,
    run_validation as run_background_bridge_validation,
)
from .code import (
    CODEWORDS,
    GENERATOR_MATRIX,
    DecodeResult,
    decode,
    decode_affine,
    encode,
    translate,
)
from .cosmology import (
    FlatLambdaCDMParameters,
    compare_distance_baselines,
    dimensionless_hubble_parameter,
    flat_lcdm_distance_curve,
    normalized_comoving_distance,
)
from .cosmological_background import (
    BackgroundParameters,
    H_km_s_Mpc,
    ash_E2,
    ash_source_xi,
    effective_w_ash,
    finite_background_features,
    integrate_background,
    lcdm_E2,
)
from .physical_perturbations import (
    PerturbationParameters,
    cmb_lowell_proxy,
    drag_eff,
    finite_kernel,
    finite_spectral_modes,
    fit_alpha_mu_grid,
    matter_grid,
    matter_power,
    mu_eff,
    solve_growth,
    synthetic_observations,
)
from .empirical import (
    CalibratedObservable,
    LikelihoodResult,
    ObservableCalibration,
    calibrate_observable,
    chi_square,
    compare_gaussian_models,
    diagonal_gaussian_log_likelihood,
)
from .hypercube import (
    distance_shell,
    distance_shell_counts,
    even_parity_shell_counts,
    hypercube_adjacency_spectrum,
    hypercube_edge_count,
    hypercube_laplacian_spectrum,
    pair_flip_adjacency_spectrum,
    pair_flip_graph_degree,
    pair_flip_graph_edge_count,
    pair_flip_laplacian_spectrum,
)
from .physics import (
    BackgroundMoments,
    PhysicsObservables,
    background_moments,
    bridge_observables,
    evolve_weight_distribution,
    mixed_sector_eigenvalue,
    mixed_sector_transition,
    payload_pair_flip_eigenvalue,
    payload_pair_flip_transition,
    payload_state_space,
    payload_to_physical_state,
    pair_flip_transition,
    physical_state_space,
    sector_refresh_eigenvalue,
    sector_refresh_transition,
    uniform_background_distribution,
    uniform_physical_distribution,
    weight_level_degeneracies,
    weight_background_kernel,
)
from .prediction_ledger import (
    canonical_prediction_hash,
    ledger_lock_status,
    validate_prediction_ledger,
)
from .observer_commitment import (
    BOUNDARY_STATEMENT as OBSERVER_COMMITMENT_BOUNDARY_STATEMENT,
    LAW_VERSION as OBSERVER_COMMITMENT_LAW_VERSION,
    BranchRecord,
    ObserverCommitmentConfig,
    commit_memory,
    commitment_distribution,
    decoherence_entry,
    decoherence_summary,
    demo_expand_tree,
    frontier,
    memory_divergence,
    parent_memory_is_prefix,
    tree_distance,
    validate_probability_weights,
    verify_memory_prefix_embedding,
    verify_r009,
)
from .unit_bridge import (
    BRIDGE_VERSION,
    bootstrap_covariance,
    bootstrap_observable_samples,
    finite_features_by_depth,
    load_calibration,
    normalize_frontier_columns,
    physical_bridge,
    validate_unit_bridge_artifacts,
)
from .finite_observer_limit import (
    ODD_LEVELS,
    LimitLevelSummary,
    UnitScaleRow,
    adjacency_spectrum as finite_observer_adjacency_spectrum,
    causal_cone_sizes,
    causal_interval_size,
    causal_related,
    edge_count as finite_observer_edge_count,
    even_states as finite_observer_even_states,
    fiber_sizes,
    graph_degree as finite_observer_graph_degree,
    hamming_distance as finite_observer_hamming_distance,
    laplacian_gap as finite_observer_laplacian_gap,
    level_summary as finite_observer_level_summary,
    pair_distance,
    project_between,
    project_state,
    shell_counts as finite_observer_shell_counts,
    unit_scale_table,
    validate_lipschitz,
    validate_projective_consistency,
    validation_summary as finite_observer_limit_validation_summary,
)

__all__ = [
    "BIT_COUNT",
    "CODEWORDS",
    "GENERATOR_MATRIX",
    "CalibratedObservable",
    "FlatLambdaCDMParameters",
    "PhysicsObservables",
    "BackgroundMoments",
    "BackgroundParameters",
    "BackgroundParams",
    "BranchRecord",
    "BRIDGE_VERSION",
    "DecodeResult",
    "H_ash",
    "H_km_s_Mpc",
    "LikelihoodResult",
    "OBSERVER_COMMITMENT_BOUNDARY_STATEMENT",
    "OBSERVER_COMMITMENT_LAW_VERSION",
    "ODD_LEVELS",
    "ObservableCalibration",
    "ObserverCommitmentConfig",
    "PerturbationParameters",
    "LimitLevelSummary",
    "UnitScaleRow",
    "angular_diameter_distance",
    "ash_E2",
    "ash_source_xi",
    "bits_to_int",
    "background_moments",
    "branch_entropy_template",
    "bootstrap_covariance",
    "bootstrap_observable_samples",
    "calibrate_observable",
    "canonical_prediction_hash",
    "chi_square",
    "cmb_lowell_proxy",
    "compare_distance_baselines",
    "compare_gaussian_models",
    "comoving_distance",
    "commit_memory",
    "commitment_distribution",
    "convergence_diagnostics",
    "decoherence_entry",
    "decoherence_summary",
    "decode",
    "decode_affine",
    "demo_expand_tree",
    "distance_shell",
    "distance_shell_counts",
    "distance_modulus",
    "diagonal_gaussian_log_likelihood",
    "dimensionless_hubble_parameter",
    "drag_eff",
    "effective_w_ash",
    "encode",
    "even_parity_shell_counts",
    "evolve_weight_distribution",
    "finite_kernel",
    "finite_spectral_modes",
    "flat_lcdm_distance_curve",
    "flip_bit",
    "fit_alpha_mu_grid",
    "frontier",
    "finite_background_features",
    "finite_features_by_depth",
    "finite_observer_adjacency_spectrum",
    "finite_observer_edge_count",
    "finite_observer_even_states",
    "finite_observer_graph_degree",
    "finite_observer_hamming_distance",
    "finite_observer_laplacian_gap",
    "finite_observer_level_summary",
    "finite_observer_limit_validation_summary",
    "finite_observer_shell_counts",
    "fiber_sizes",
    "hamming_distance",
    "hamming_weight",
    "hypercube_adjacency_spectrum",
    "hypercube_edge_count",
    "hypercube_laplacian_spectrum",
    "int_to_bits",
    "integrate_background",
    "integrity_bit",
    "is_integrity_valid",
    "ledger_lock_status",
    "lcdm_E2",
    "load_calibration",
    "make_integrity_state",
    "matter_grid",
    "matter_power",
    "memory_divergence",
    "bridge_observables",
    "mixed_sector_eigenvalue",
    "mixed_sector_transition",
    "mu_eff",
    "normalized_comoving_distance",
    "normalize_frontier_columns",
    "payload_pair_flip_eigenvalue",
    "payload_pair_flip_transition",
    "payload_state_space",
    "payload_to_physical_state",
    "pair_distance",
    "pair_flip_adjacency_spectrum",
    "pair_flip_graph_degree",
    "pair_flip_graph_edge_count",
    "pair_flip_laplacian_spectrum",
    "pair_flip_transition",
    "parent_memory_is_prefix",
    "physical_bridge",
    "physical_state_space",
    "posterior_from_grid",
    "causal_cone_sizes",
    "causal_interval_size",
    "causal_related",
    "project_between",
    "project_state",
    "run_background_bridge_validation",
    "sector_refresh_eigenvalue",
    "sector_refresh_transition",
    "solve_growth",
    "synthetic_observations",
    "translate",
    "tree_distance",
    "unit_scale_table",
    "uniform_physical_distribution",
    "uniform_background_distribution",
    "validate_lipschitz",
    "validate_prediction_ledger",
    "validate_projective_consistency",
    "validate_probability_weights",
    "validate_unit_bridge_artifacts",
    "verify_memory_prefix_embedding",
    "verify_r009",
    "weight_level_degeneracies",
    "weight_background_kernel",
    "xor_bits",
]

__version__ = "1.1.0"
